# Generated by Django 4.0.4 on 2022-07-15 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('support_id', models.TextField(default=supports.models.create_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destek',
                'verbose_name_plural': 'Destek Talepleri',
            },
        ),
        migrations.CreateModel(
            name='AnswerSupport',
            fields=[
                ('answer_id', models.TextField(default=supports.models.create_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alıcı', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gönderici', to=settings.AUTH_USER_MODEL)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supports.support')),
            ],
            options={
                'verbose_name': 'Destek Cevabı',
                'verbose_name_plural': 'Destek Cevapları',
            },
        ),
    ]
