# Generated by Django 4.0.4 on 2022-07-15 11:04

from django.db import migrations, models
import django.db.models.deletion
import supports.models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRoom',
            fields=[
                ('room_id', models.TextField(default=supports.models.create_id, editable=False, max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Oda',
                'verbose_name_plural': 'Destek Odaları',
            },
        ),
        migrations.AddField(
            model_name='answersupport',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supports.supportroom'),
        ),
        migrations.AddField(
            model_name='support',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supports.supportroom'),
        ),
    ]
