# Generated by Django 5.0.4 on 2024-08-07 18:29

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Duyuru Adı')),
                ('image', models.ImageField(upload_to='backend/img/announcement', verbose_name='Duyuru Resmi')),
                ('detail', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Detay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Duyurular',
                'verbose_name_plural': 'Duyurular',
            },
        ),
        migrations.CreateModel(
            name='MarketPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pazaryeri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Pazaryerleri',
                'verbose_name_plural': 'Pazaryerleri',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('detail', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Detay')),
            ],
            options={
                'verbose_name': 'Abonelik Tipleri',
                'verbose_name_plural': 'Abonelik Tipleri',
            },
        ),
        migrations.CreateModel(
            name='SupportedTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Tip Adı')),
                ('image', models.ImageField(upload_to='backend/img/ecommerce', verbose_name='XML Resmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Desteklenen Tipler',
                'verbose_name_plural': 'Desteklenen Tipler',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, null=True, verbose_name='IP')),
                ('read_date', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.announcement', verbose_name='Duyurular')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Müşteri Adı')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Müşteri Soyadı')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Müşteri E-Posta')),
                ('mobile', models.CharField(max_length=100, null=True, verbose_name='Müşteri Telefonu')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.subscriptiontype', verbose_name='Abonelik Tipi')),
            ],
            options={
                'verbose_name': 'Müşteriler',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.DeleteModel(
            name='EcommerceEntegration',
        ),
    ]
