# Generated by Django 5.0.4 on 2024-08-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_announcement_marketplaces_subscriptiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
