# Generated by Django 5.0.4 on 2024-08-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_customer_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
