# Generated by Django 5.0.4 on 2024-08-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_marketplaces_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaces',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
