# Generated by Django 5.0.4 on 2024-08-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_marketplaces_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedtypes',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
