# Generated by Django 5.0.4 on 2024-06-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Duyuru Başlık')),
                ('content', models.TextField(verbose_name='Duyuru İçeriği')),
                ('importance', models.CharField(max_length=255, null=True, verbose_name='Duyuru Önceliği')),
                ('type_choices', models.CharField(choices=[('Soru', 'Soru'), ('Kayıt Onay', 'Kayıt Onay'), ('İş Teklifi', 'İş Teklifi')], max_length=50, null=True, verbose_name='Duyuru Tipi')),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
            },
        ),
    ]
