# Generated by Django 4.0.4 on 2022-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
