# Generated by Django 4.0.4 on 2022-07-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='importance',
            field=models.CharField(max_length=255, null=True, verbose_name='Duyuru Önceliği'),
        ),
    ]
