# Generated by Django 4.0.4 on 2022-07-14 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0003_announcement_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='users',
        ),
        migrations.AddField(
            model_name='announcement',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
