# Generated by Django 4.0.4 on 2022-07-24 07:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Genel'), ('2', 'HTML/Css'), ('3', 'Javasciprt'), ('4', 'Python'), ('5', 'Django'), ('6', 'Yapay Zeka'), ('7', 'Teknoloji')], max_length=20, null=True, verbose_name='Kategori')),
                ('category_slug', models.SlugField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='static/img/blog/', verbose_name='Blog Resmi')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('keywords', models.CharField(max_length=100, verbose_name='Anahtar Kelime')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('blog_views', models.IntegerField(blank=True, default=0, null=True)),
                ('is_main_slider', models.BooleanField(default=False, null=True, verbose_name='Ana Slider')),
                ('mainslider_choice_date', models.DateTimeField(null=True, verbose_name='Ana Slider Seçim Tarihi')),
                ('is_main_choice', models.BooleanField(default=False, null=True)),
                ('main_choice_date', models.DateTimeField(verbose_name='Seçim Tarihi')),
                ('is_other_choice', models.BooleanField(default=False, null=True)),
                ('other_choice_date', models.DateTimeField(verbose_name='Seçim Tarihi')),
                ('is_avalabile', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=1000, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Blog Gönderisi',
                'verbose_name_plural': 'Blog Gönderileri',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Yorum ve Oylama Sistemi',
                'verbose_name_plural': 'Yorum ve Oylama Sistemi',
            },
        ),
    ]
