# Generated by Django 4.0.4 on 2022-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('1', 'Genel'), ('2', 'HTML/Css'), ('3', 'Javasciprt'), ('4', 'Python'), ('5', 'Django'), ('6', 'Yapay Zeka'), ('7', 'Teknoloji')], max_length=20, null=True, verbose_name='Kategori'),
        ),
    ]
