# Generated by Django 3.2.3 on 2022-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_subscribe',
            field=models.BooleanField(default=True, null=True, verbose_name='İletişim ve Reklam Onayı'),
        ),
    ]
