# Generated by Django 4.0.4 on 2022-07-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
    ]
