# Generated by Django 4.0.4 on 2022-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_approved',
            field=models.BooleanField(default=False, null=True, verbose_name='Sözleşmelerin Onayı'),
        ),
    ]
