# Generated by Django 4.0.4 on 2022-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name': 'Hesap Silme Neden',
                'verbose_name_plural': 'Hesap Silme Nedenleri',
            },
        ),
    ]
