# Generated by Django 4.0.4 on 2022-05-10 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=60, verbose_name='Soyisim')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300, null=True, verbose_name='Adres')),
                ('is_admin', models.BooleanField(default=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/admin_photo/', verbose_name='Yönetici Fotoğrafı')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_exist', models.BooleanField(default=False, null=True)),
                ('authorizedperson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Kişi')),
            ],
            options={
                'verbose_name': 'Yönetici',
                'verbose_name_plural': 'Yöneticiler',
            },
        ),
    ]
