# Generated by Django 4.0.4 on 2022-07-24 07:17

import adminpage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.TextField(default=adminpage.models.task_create_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=500, null=True, verbose_name='Müşteri İsmi')),
                ('customer_email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Müşteri Email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Müşteri Telefon')),
                ('task_name', models.CharField(max_length=500, null=True, verbose_name='Görev Adı')),
                ('task_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Görev Ücreti')),
                ('task_start_date', models.DateField()),
                ('estimated_deliver_date', models.DateField()),
                ('is_exist', models.BooleanField(default=True)),
                ('authorizedperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Kişi')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.TextField(default=adminpage.models.note_create_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=100, null=True, verbose_name='Not Başlık')),
                ('note_content', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Not İçerik')),
                ('task_start_date', models.DateField(auto_now=True)),
                ('is_exist', models.BooleanField(default=True)),
                ('authorizedperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Kişi')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=60, verbose_name='Soyisim')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300, null=True, verbose_name='Adres')),
                ('is_admin', models.BooleanField(default=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/admin_photo/', verbose_name='Yönetici Fotoğrafı')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_exist', models.BooleanField(default=False, null=True)),
                ('authorizedperson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Kişi')),
            ],
            options={
                'verbose_name': 'Yönetici',
                'verbose_name_plural': 'Yöneticiler',
            },
        ),
    ]
