# Generated by Django 4.0.4 on 2022-05-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=500, null=True, verbose_name='Müşteri İsmi')),
                ('customer_email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Müşteri Email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Müşteri Telefon')),
                ('task_name', models.CharField(max_length=500, null=True, verbose_name='Görev Adı')),
                ('task_price', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Görev Ücreti')),
                ('task_start_date', models.DateField()),
                ('estimated_deliver_date', models.DateField()),
                ('is_exist', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
            },
        ),
    ]
