# Generated by Django 4.0.4 on 2022-05-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpage', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='authorizedperson',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Kişi'),
            preserve_default=False,
        ),
    ]
