# Generated by Django 5.0.4 on 2024-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_blogcategory_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Yayınla', 'Yayınla'), ('Taslak', 'Taslak'), ('Askıya Al', 'Askıya Al')], default='Yayınla', max_length=100, null=True),
        ),
    ]
