# Generated by Django 5.0.4 on 2024-04-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Açıklama'),
        ),
    ]
