# Generated by Django 4.0.4 on 2022-05-16 21:00

import adminpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_task_authorizedperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.TextField(default=adminpage.models.task_create_id, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
