# Generated by Django 4.0.4 on 2022-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_remove_task_id_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Görev Ücreti'),
        ),
    ]
