# Generated by Django 4.0.4 on 2022-05-18 20:16

import adminpage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpage', '0006_alter_task_authorizedperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.TextField(default=adminpage.models.note_create_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=100, null=True, verbose_name='Not Başlık')),
                ('note_content', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Not İçerik')),
                ('task_start_date', models.DateField(auto_now=True)),
                ('is_exist', models.BooleanField(default=True)),
                ('authorizedperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Kişi')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
            },
        ),
    ]
