# Generated by Django 5.0.4 on 2024-06-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_keywords',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='udemy_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
