# Generated by Django 5.0.4 on 2024-06-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_alter_sitesettings_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
