# Generated by Django 5.0.4 on 2024-06-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_sitesettings_site_whatsapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
