# Generated by Django 4.0.4 on 2022-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_image', models.ImageField(upload_to='img/', verbose_name='Büyük Resim')),
                ('small_image', models.ImageField(upload_to='img/', verbose_name='Küçük Resim')),
                ('slider_title', models.CharField(max_length=100, verbose_name='Slider Başlık')),
                ('content', models.CharField(blank=True, max_length=250, null=True, verbose_name='Slider İçerik')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slider_ids', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Ana Slider',
                'verbose_name_plural': 'Ana Slider',
            },
        ),
    ]
