# Generated by Django 5.0.4 on 2024-06-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainslider',
            name='shape1',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape10',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape2',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape3',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape4',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape5',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape6',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape7',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape8',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='shape9',
        ),
    ]
