# Generated by Django 4.0.4 on 2022-07-16 10:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('content', models.TextField(max_length=2000, verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Fiyat Teklif Mesaj',
                'verbose_name_plural': 'Fiyat Teklif Mesajları',
            },
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='large_image',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='small_image',
        ),
        migrations.AddField(
            model_name='mainslider',
            name='details_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/detay/', verbose_name='Detay Fotoğraf (872 x 510)'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='1. Fotoğraf (424 x 502)'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='2. Fotoğraf (376 x 376)'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape1',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='1. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape10',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='10. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape2',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='2. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape3',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='3. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape4',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='4. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape5',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='5. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape6',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='6. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape7',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='7. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape8',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='8. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='shape9',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='9. Shape'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='sub_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='text',
            field=models.CharField(max_length=300, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='slider_title',
            field=models.CharField(max_length=150, null=True, verbose_name='Slider Başlık'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='slug',
            field=models.SlugField(max_length=1000, null=True),
        ),
    ]
