# Generated by Django 5.0.4 on 2024-06-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_mainslider_slider_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'ordering': ['-create_at'], 'verbose_name': 'Ana Slider', 'verbose_name_plural': 'Ana Slider'},
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='img/slider/', verbose_name='1. Fotoğraf (424 x 502)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='img/slider', verbose_name='2. Fotoğraf (376 x 376)'),
        ),
    ]
