# Generated by Django 5.0.4 on 2024-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_mainslider_options_alter_mainslider_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
