# Generated by Django 5.0.4 on 2024-07-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Yazısı'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buton URL'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='redirecting',
            field=models.BooleanField(default=False),
        ),
    ]
