# Generated by Django 4.0.4 on 2022-07-21 13:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_websiteconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSitePrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Başlık')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('create_at', models.DateTimeField()),
                ('data_officer', models.CharField(max_length=255, null=True, verbose_name='Veri Sorumlusu')),
                ('data_officer_address', models.CharField(max_length=500, null=True, verbose_name='Veri Sorumlusu Adresi')),
            ],
            options={
                'verbose_name': 'Gizlilik Politikası',
                'verbose_name_plural': 'Gizlilik Politikası',
            },
        ),
    ]
