# Generated by Django 4.0.4 on 2022-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_websiteprivacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteprivacy',
            name='data_country',
            field=models.CharField(max_length=255, null=True, verbose_name='Verinin İşlendiği Ülkeler'),
        ),
    ]
