# Generated by Django 5.0.4 on 2024-07-21 17:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_mainslider_button_text_mainslider_button_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
