# Generated by Django 4.0.4 on 2022-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_websiteprivacy_data_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSiteCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_provider', models.CharField(max_length=500, null=True, verbose_name='Cookie Sağlayıcısı')),
                ('cookie_name', models.CharField(max_length=500, null=True, verbose_name='Cookie İsmi')),
                ('cookie_aim', models.CharField(max_length=500, null=True, verbose_name='Cookie Amacı')),
                ('cookie_type', models.CharField(max_length=500, null=True, verbose_name='Cookie Tipi')),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Çerezler',
                'verbose_name_plural': 'Çerezler',
            },
        ),
    ]
