# Generated by Django 4.0.4 on 2022-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_websitekvkk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteprivacy',
            name='data_country',
            field=models.CharField(max_length=5000, null=True, verbose_name='Verinin İşlendiği Ülkeler'),
        ),
    ]
