# Generated by Django 4.0.4 on 2022-05-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Hesaplar', 'verbose_name_plural': 'Hesaplar'},
        ),
    ]
