# Generated by Django 5.0.4 on 2024-05-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpage', '0006_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Kayıtlı E-Posta')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onay Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.education')),
            ],
        ),
    ]
