# Generated by Django 5.0.4 on 2024-05-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_education'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducation',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentEducation', to='adminpage.education'),
        ),
    ]
