# Generated by Django 5.0.4 on 2024-05-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_announcements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='StudentAnnouncements',
        ),
    ]
