# Generated by Django 5.0.4 on 2024-06-09 07:41

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_sitesettings_site_whatsapp'),
        ('student', '0005_studenteducation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Soru Başlığı')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Yazı')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Onay Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.education')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
        ),
    ]
