# Generated by Django 4.0.4 on 2022-07-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
    ]
